[package]
name = "contract"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
eosio = { path = "../../eosio-rust/eosio" }
